language: node_js
## Set a specific version of Yarn below
## https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#using-yarn
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
    - export PATH="$HOME/.yarn/bin:$PATH"
    - yarn --version
before_script:
    - cat yarn.lock
    - yarn jest --version
cache:
    yarn: true
