module.exports = {
    '@thumbtack/tp-ui-react-avatar': 'Avatar',
    '@thumbtack/tp-ui-react-button': 'Button',
    '@thumbtack/tp-ui-react-button-row': 'ButtonRow',
    '@thumbtack/tp-ui-react-carousel': 'Carousel',
    '@thumbtack/tp-ui-react-checkbox': 'Checkbox',
    '@thumbtack/tp-ui-react-date-picker': 'DatePicker',
    '@thumbtack/tp-ui-react-form-note': 'FormNote',
    '@thumbtack/tp-ui-react-input': 'Input',
    '@thumbtack/tp-ui-react-input-row': 'InputRow',
    '@thumbtack/tp-ui-react-label': 'Label',
    '@thumbtack/tp-ui-react-link': 'Link',
    '@thumbtack/tp-ui-react-loader-dots': 'LoaderDots',
    '@thumbtack/tp-ui-react-modal-base': 'ModalBase',
    '@thumbtack/tp-ui-react-modal-curtain': 'ModalCurtain',
    '@thumbtack/tp-ui-react-modal-default': 'ModalDefault',
    '@thumbtack/tp-ui-react-modal-standard': 'ModalStandard',
    '@thumbtack/tp-ui-react-progress-bar': 'ProgressBar',
    '@thumbtack/tp-ui-react-progress-bar-base': 'ProgressBarBase',
    '@thumbtack/tp-ui-react-radio': 'Radio',
    '@thumbtack/tp-ui-react-select': 'Select',
    '@thumbtack/tp-ui-react-service-card': 'ServiceCard',
    '@thumbtack/tp-ui-react-star-rating': 'StarRating',
    '@thumbtack/tp-ui-react-textarea': 'Textarea',
    '@thumbtack/tp-ui-react-tooltip': 'Tooltip',
    '@thumbtack/tp-ui-react-wrap': 'Wrap',
};
