/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

description = "Design variables that power Thumbtack’s UI."
version = "0.0.0"
buildDir = file("${projectDir}/dist/android")

defaultTasks("buildDist")

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.31")
    `maven-publish`
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()

    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    implementation("com.github.srs:gradle-node-plugin:1.3.1")
}

tasks.register<Exec>("buildDist") {
    commandLine("which", "yarn")
    commandLine("yarn", "start")
}

tasks.register<Jar>("tokensJar") {
    dependsOn("buildDist")
    from("${projectDir}/dist/android/index.xml")
    archiveClassifier.set("tokens")
}

publishing {
    publications {
        create<MavenPublication>("maven") {

            artifact(tasks["tokensJar"])
        }
    }
}
